"""Ajout des tables ou colonnes manquantes

Revision ID: 0274920a0da2
Revises: 4dcdb4413e67
Create Date: 2024-10-17 19:46:11.031143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0274920a0da2'
down_revision = '4dcdb4413e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('pdf_data')

    # ### end Alembic commands ###
