"""Rename User to Form and create form table

Revision ID: 4dcdb4413e67
Revises: b837a12b407e
Create Date: 2024-10-17 19:14:09.204556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcdb4413e67'
down_revision = 'b837a12b407e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('implantation', sa.String(length=120), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('billing_address', sa.String(length=250), nullable=False),
    sa.Column('shipping_address', sa.String(length=250), nullable=False),
    sa.Column('reason', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('implantation', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('billing_address', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('shipping_address', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('other_reason', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.drop_table('form')
    # ### end Alembic commands ###
