"""Initial migration

Revision ID: b837a12b407e
Revises: 8a134d7c908c
Create Date: 2024-10-17 12:08:32.881181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b837a12b407e'
down_revision = '8a134d7c908c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('implantation', sa.String(length=120), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('billing_address', sa.String(length=250), nullable=False),
    sa.Column('shipping_address', sa.String(length=250), nullable=False),
    sa.Column('reason', sa.String(length=250), nullable=False),
    sa.Column('other_reason', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form')
    # ### end Alembic commands ###
